name: 'auto-spaceship'
description: 'Wait a designated number of milliseconds'
inputs:
  apple_id:
    description: 'The Apple ID you will log in with'
    required: true
  apple_password:
    description: 'Your Apple ID password'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
