name: "units-test"
on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        apple_id: ${{ secrets.APPLE_ID }}
        apple_password: ${{ secrets.APPLE_PASSWORD }}
        tfa_phone_number: ${{ secrets.PHONE_NUMBER }}
        github_pat: ${{ secrets.GH_PAT }}
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
